#!/usr/bin/env bash
# Runs inside every node container. Expects these env vars (set per-node in
# docker-compose.yml, generated by 03-generate-compose.py):
#   NODE_TIER        core | edge | mobile
#   TC_DELAY_MS       e.g. 300
#   TC_JITTER_MS      e.g. 50
#   TC_RATE_MBIT      e.g. 10
#   TC_LOSS_PCT       e.g. 5
#   NODE_NAME         e.g. node14
set -euo pipefail

IFACE="eth0"

echo "[${NODE_NAME}] tier=${NODE_TIER} applying tc netem: " \
     "delay=${TC_DELAY_MS}ms(+/-${TC_JITTER_MS}ms) rate=${TC_RATE_MBIT}mbit loss=${TC_LOSS_PCT}%"

# Requires the container to run with --cap-add=NET_ADMIN (set in docker-compose.yml).
# Build the delay clause conditionally so jitter=0 tiers (core) don't get a
# spurious " 0ms" suffix.
if [ "${TC_JITTER_MS}" -gt 0 ]; then
  DELAY_CLAUSE="delay ${TC_DELAY_MS}ms ${TC_JITTER_MS}ms distribution normal"
else
  DELAY_CLAUSE="delay ${TC_DELAY_MS}ms"
fi

tc qdisc add dev "${IFACE}" root handle 1: netem \
    ${DELAY_CLAUSE} \
    loss ${TC_LOSS_PCT}%

tc qdisc add dev "${IFACE}" parent 1: handle 2: tbf \
    rate ${TC_RATE_MBIT}mbit burst 32kbit latency 400ms

echo "[${NODE_NAME}] tc rules applied:"
tc qdisc show dev "${IFACE}"

mkdir -p /data/logs

# Not using `exec` here: we need besu's stdout teed to a file on the mounted
# volume so monitoring/collect_metrics.py can grep for round-change events
# after the run. `tee` also keeps output visible via `docker logs`.
besu \
  --data-path=/data \
  --genesis-file=/config/genesis.json \
  --node-private-key-file=/data/key.priv \
  --p2p-host=0.0.0.0 \
  --p2p-port=30303 \
  --rpc-http-enabled \
  --rpc-http-host=0.0.0.0 \
  --rpc-http-port=8545 \
  --rpc-http-api=ETH,QBFT,NET,ADMIN \
  --rpc-ws-enabled \
  --rpc-ws-host=0.0.0.0 \
  --rpc-ws-port=8546 \
  --host-allowlist="*" \
  --rpc-http-cors-origins="*" \
  --min-gas-price=0 \
  --logging=INFO \
  --bootnodes="${BOOTNODES}" \
  2>&1 | tee "/data/logs/${NODE_NAME}.log"
