#!/usr/bin/env python3
"""
Reads the validator keys generated by 01-generate-network.sh and assigns each
of the 24 nodes to one of three tiers:

  - core   (0-5)   : delay=10ms,  rate=100Mbit, loss=0%
  - edge   (6-13)  : delay=100ms, rate=50Mbit,  loss=0%
  - mobile (14-23) : delay=300ms, rate=10Mbit,  loss=5%, jitter=50ms

Writes networkFiles/topology.json which downstream scripts (compose generator,
entrypoint, workload/monitoring scripts) all read from — single source of truth.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEYS_DIR = os.path.join(ROOT, "networkFiles", "keys")
OUT_FILE = os.path.join(ROOT, "networkFiles", "topology.json")

SUBNET_PREFIX = "172.28.0"  # gurubft-net subnet: 172.28.0.0/24
BASE_HOST_RPC_PORT = 8545
BASE_HOST_WS_PORT = 8546
P2P_PORT = 30303

TIER_PROFILES = {
    "core":   {"delay_ms": 10,  "rate_mbit": 100, "loss_pct": 0,   "jitter_ms": 0},
    "edge":   {"delay_ms": 100, "rate_mbit": 50,  "loss_pct": 0,   "jitter_ms": 10},
    "mobile": {"delay_ms": 300, "rate_mbit": 10,  "loss_pct": 5,   "jitter_ms": 50},
}


def tier_for_index(i: int) -> str:
    if i < 6:
        return "core"
    elif i < 14:
        return "edge"
    else:
        return "mobile"


def main():
    addresses = sorted(os.listdir(KEYS_DIR))
    if len(addresses) != 15 :
        raise SystemExit(
            f"Expected 15 validator keys, found {len(addresses)}. "
            "Re-run 01-generate-network.sh."
        )

    nodes = []
    for i, addr in enumerate(addresses):
        tier = tier_for_index(i)
        node = {
            "index": i,
            "name": f"node{i:02d}",
            "tier": tier,
            "address": addr,
            "ip": f"{SUBNET_PREFIX}.{10 + i}",
            "p2p_port": P2P_PORT,
            "host_rpc_port": BASE_HOST_RPC_PORT + i,
            "host_ws_port": BASE_HOST_WS_PORT + 30 + i,
            "profile": TIER_PROFILES[tier],
        }
        nodes.append(node)

    topology = {"subnet": f"{SUBNET_PREFIX}.0/24", "nodes": nodes}
    with open(OUT_FILE, "w") as f:
        json.dump(topology, f, indent=2)

    counts = {"core": 0, "edge": 0, "mobile": 0}
    for n in nodes:
        counts[n["tier"]] += 1
    print(f"Wrote {OUT_FILE}")
    print(f"Tier distribution: {counts}")


if __name__ == "__main__":
    main()
