#!/usr/bin/env python3
"""
Reads the validator keys generated by 01-generate-network.sh and spreads the
15 nodes across 5 geographic regions (3 nodes per region) to emulate a WAN:

  - us-east, us-west, eu-west, ap-southeast, sa-east

Latency depends on the (source region, destination region) pair, using an
approximate inter-region RTT matrix. One-way delay applied with tc netem is
RTT/2 on each side. Each node gets a per-destination list of egress rules
that the entrypoint can turn into tc (prio/htb + netem + u32 dst filters).

Writes networkFiles/topology.json — single source of truth for downstream
scripts (compose generator, entrypoint, workload/monitoring scripts).
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEYS_DIR = os.path.join(ROOT, "networkFiles", "keys")
OUT_FILE = os.path.join(ROOT, "networkFiles", "topology.json")

SUBNET_PREFIX = "172.28.0"  # gurubft-net subnet: 172.28.0.0/24
BASE_HOST_RPC_PORT = 8545
BASE_HOST_WS_PORT = 8546
P2P_PORT = 30303
NUM_NODES = 15

REGIONS = ["us-east", "us-west", "eu-west", "ap-southeast", "sa-east"]

# Approximate round-trip times between regions (ms).
RTT_MS = {
    ("us-east", "us-west"):        65,
    ("us-east", "eu-west"):        80,
    ("us-east", "ap-southeast"):  220,
    ("us-east", "sa-east"):       120,
    ("us-west", "eu-west"):       140,
    ("us-west", "ap-southeast"):  170,
    ("us-west", "sa-east"):       175,
    ("eu-west", "ap-southeast"):  160,
    ("eu-west", "sa-east"):       190,
    ("ap-southeast", "sa-east"):  320,
}
INTRA_REGION_RTT_MS = 2

# Link characteristics shared by all WAN links.
RATE_MBIT = 100          # per-node egress cap
JITTER_FRACTION = 0.05   # jitter = 5% of one-way delay
LOSS_PCT_INTER = 0.1     # loss on inter-region links
LOSS_PCT_INTRA = 0.0


def rtt(a: str, b: str) -> int:
    if a == b:
        return INTRA_REGION_RTT_MS
    return RTT_MS.get((a, b)) or RTT_MS[(b, a)]


def region_for_index(i: int) -> str:
    # Round-robin so consecutive indices (and thus QBFT proposer rotation)
    # alternate across regions.
    return REGIONS[i % len(REGIONS)]


def link_profile(src_region: str, dst_region: str) -> dict:
    one_way = rtt(src_region, dst_region) / 2
    intra = src_region == dst_region
    return {
        "delay_ms": round(one_way, 1),
        "jitter_ms": round(one_way * JITTER_FRACTION, 1),
        "loss_pct": LOSS_PCT_INTRA if intra else LOSS_PCT_INTER,
        "rate_mbit": RATE_MBIT,
    }


def main():
    addresses = sorted(os.listdir(KEYS_DIR))
    if len(addresses) != NUM_NODES:
        raise SystemExit(
            f"Expected {NUM_NODES} validator keys, found {len(addresses)}. "
            "Re-run 01-generate-network.sh."
        )

    # First pass: base node info
    nodes = []
    for i, addr in enumerate(addresses):
        nodes.append({
            "index": i,
            "name": f"node{i:02d}",
            "region": region_for_index(i),
            "address": addr,
            "ip": f"{SUBNET_PREFIX}.{10 + i}",
            "p2p_port": P2P_PORT,
            "host_rpc_port": BASE_HOST_RPC_PORT + i,
            "host_ws_port": BASE_HOST_WS_PORT + 30 + i,
        })

    # Second pass: per-destination egress rules for each node
    for src in nodes:
        src["egress_rules"] = [
            {
                "dst_name": dst["name"],
                "dst_ip": dst["ip"],
                "dst_region": dst["region"],
                **link_profile(src["region"], dst["region"]),
            }
            for dst in nodes if dst["index"] != src["index"]
        ]

    latency_matrix = {
        a: {b: rtt(a, b) for b in REGIONS} for a in REGIONS
    }

    topology = {
        "subnet": f"{SUBNET_PREFIX}.0/24",
        "regions": REGIONS,
        "rtt_matrix_ms": latency_matrix,
        "nodes": nodes,
    }
    with open(OUT_FILE, "w") as f:
        json.dump(topology, f, indent=2)

    counts = {r: 0 for r in REGIONS}
    for n in nodes:
        counts[n["region"]] += 1
    print(f"Wrote {OUT_FILE}")
    print(f"Region distribution: {counts}")


if __name__ == "__main__":
    main()